compat: remove redefinition of __truncdfsf2
Not required since it was added in the compilter_builtins repository
in December 2021 [0].

[0]: https://github.com/rust-lang/compiler-builtins/commit/67c763f4e9a2f1600612953ff38c68661367954a

Else the linker gets confused over the duplicate symbols.

> note: rust-lld: error: duplicate symbol: __truncdfsf2
>           >>> defined at common.rs:325 (src/compat/common.rs:325)
>           >>>            bl602wifi-76a5cd24729b8332.bl602wifi.8c259872-cgu.1.rcgu.o:(__truncdfsf2) in archive /home/tom/pool/sources/bl602/bl602-wifi-rs/target/riscv32imfc-unknown-none-elf/release/deps/libbl602wifi-76a5cd24729b8332.rlib
>           >>> defined at bit.rs:174 (/home/tom/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/bit.rs:174)
>           >>>            compiler_builtins-3819d9611b8351e0.compiler_builtins.1a32524b-cgu.11.rcgu.o:(.text.__truncdfsf2+0x0) in archive /home/tom/pool/sources/bl602/bl602-wifi-rs/target/riscv32imfc-unknown-none-elf/release/deps/libcompiler_builtins-3819d9611b8351e0.rlib

Signed-off-by: Thomas Lamprecht <t.lamprecht@proxmox.com>